[profile.default]
src = "src"
test = "test"
out = "out"
libs = []
solc = "0.8.26"
evm_version = "paris"
optimizer = true
optimizer_runs = 200
bytecode_hash = "none"
remappings = [
    "@layerzerolabs/=src/vendor/@layerzerolabs/",
    "@openzeppelin/=src/vendor/@openzeppelin/",
    "forge-std/=test/vendor/forge-std/",
]

[profile.default.fuzz]
runs = 256

[fmt]
ignore = ["src/vendor/**", "test/vendor/**"]
